### ISSUE TITLE
Pause at startup

### ISSUE THREAD

**Issue by landswellsong** [IonosatMicro/promis-backend#38]
PostGIS instance takes a while to initialise and more often than not, the backend tries to connect to an unprepared database and fails to. The workaround is to `reload` the container, but that is hardly elegant. Please increase the timeout during which the backend waits for the database to become available or implement anything of this kind to fix it.

**Comment by lyssdod** [comment]
How many time it needs to wait?

**Comment by landswellsong** [comment]
@lyssdod: no idea, investigating this is part of the task. I can see this reproduced at 3 setups at least (Mac, Gentoo, @elpiankova's Ubuntu)

**Comment by landswellsong** [comment]
@lyssdod timeout won't help, when Postgres is starting up the server sends `RST` on TCP requests. That's actually documented in the `postgres` image help. I'm making a workaround, this issue is mine now.

**Comment by landswellsong** [comment]
```
$ docker logs api.promis
=> Database not available, retrying in 3 seconds
=> Database not available, retrying in 3 seconds
=> Database not available, retrying in 3 seconds
=> Database not available, retrying in 3 seconds
=> Database is available and accepting queries, starting PROMIS
Migrations for 'backend_api':
  promis/backend_api/migrations/0001_initial.py:
    - Create model Channel
    - Create model ChannelTranslation
    - Create model Device
    - Create model DeviceTranslation
```

It's do!
