### ISSUE TITLE
Role interface

### ISSUE THREAD

**Issue by lyssdod** [IonosatMicro/promis-backend#41]
Need to provide few roles with various access rights, also need to bind new user to default role during registration

**Comment by elpiankova** [comment]
Default role "general" should have 
- 'Default get data' custom permission.

For creation roles (groups) via admin interface, we need to have the next custom permissions:
- [ ] 'Default get data': to get measurement data (download and quick-look document) by `par_doc_id` in 6 months from `time_begin` of session
- [ ] 'Get 2 level data': to get measurement data (download and quick-look document) by `par_doc_id`
- [ ] 'Get 1 level data': to get measurement data (download and quick-look document) by `chn_doc_id`
