### ISSUE TITLE
Port in API urls

### ISSUE THREAD

**Issue by landswellsong** [IonosatMicro/promis-backend#60]
The URL generated in the responses don't have the correct port. Please inform me if you need anything additional given on the `deploy` side.

**Comment by lyssdod** [comment]
I will fix the api root view, for responses it's possible to use `request.META['SERVER_PORT']`

**Comment by landswellsong** [comment]
It does however work with the hostname (local alias in my case).

![screen shot 2017-03-23 at 17 58 38](https://cloud.githubusercontent.com/assets/2434329/24257037/67370526-0ff2-11e7-8ee3-f7aef5d7e69d.png)

**Comment by landswellsong** [comment]
See the `PROMIS_ORIGIN` env variable (pull pending)
