### ISSUE TITLE
Debugging switch

### ISSUE THREAD

**Issue by landswellsong** [IonosatMicro/promis-backend#7]
Make sure that the Django `Debug` option is only active when `development_mode` is set. Refer to: https://github.com/IonosatMicro/promis-backend/blob/skeleton/promis/promis/settings.py#L26
- [ ] Debugging switch
- [ ] Host infromation
- [ ] Keys, passwords

**Comment by landswellsong** [comment]
@0486 FYI, relevant environment variables:
- `POSTGRES_USER`
- `POSTGRES_PASSWORD`
- `POSTGRES_DB`
- `POSTGRES_HOST`
- `POSTGRES_PORT` (currently working)
- `DJANGO_DEBUG` 
- `DJANGO_SECRET` (will be working soon)

**Comment by lyssdod** [comment]
@landswellsong providing that much db info is not effective. Better way is to utilize https://github.com/kennethreitz/dj-database-url module and pass only one variable (`DATABASE_URL`) inside

**Comment by landswellsong** [comment]
@lyssdod roger that
