### ISSUE TITLE
Logging out gives a 500 error

### ISSUE THREAD

**Issue by landswellsong** [IonosatMicro/promis-backend#78]
Steps to reproduce:
1. Log in
2. Navigate to an API URL
3. Log out

You get a generic 500 page with no content instead of Django's generated UI showing that you no longer have access here. Also related to #77

**Comment by landswellsong** [comment]
May be related. Steps to reproduce:
1. Login in as `promis`
2. Go to `/en/api/quicklook/1`
3. Log out
4. See this:
![image](https://cloud.githubusercontent.com/assets/2434329/24839319/7df0d6d6-1d60-11e7-8615-b8fc0eadb6b8.png)

**Comment by 0486** [comment]
fixed
